language: node_js
node_js:
- '8'

script:
- yarn test:cov
- yarn build

deploy:
  provider: npm
  email: rolandjitsu@gmail.com
  api_key:
    secure: RkWh74sfkCq+00Pv+3zWhoFXHpu6Ka5kRvyCZnhauANOFQiTiewPSbwkdsHbIimn3rdSezuU6untSTYOazE2lJ5GsA12mZhwNELx5Cl0PRDuCJIpEb7C3pGYZqtZdlca1PhgSIJuc81nU5n4k+4P6Snia1hz9sEqJV/hnpojTxDuewz4o0XBI61QIObtfbsl890KwhjSVPQcjsi9b1i3t1SLBCHM6AuNawF0IED1SmSDyXSjLC89xUmp/5lbrHkXuNwAM18UA9ZW7sMDNdRKNTut3JKfF01hiE+FsXNqfyFdekKuEkWYLWyD9hp+u2xDf3fNPiwq8rcKab+kKi9wQ1cV6e8otExDKeK2hqRdvKRMiFpe+7AN8K9b1SXzV49+2GBH2Gln9M4/IjG4P2C2dJTM80uH6P9M2uBh0LsBwAOpB/mOBXcV/Jqjo69raqA1swQ43tdFQuv7/3GRde1Dl0Av6HMCMFuFFkqKizdxuwD2xbkVziMwkBtflEC1dAHzrRase1RIVdMF+E3p64Bt/L4ISMgJONwASagxB2WbIPDbN7xnqJr5B9NUw55sUiIHFx3jTpz+1zES2nqXnS3Oes5g+1R3QHnzUDCaJWqaGTibKgjv7tuaOxJ8ZaroRCB28d6pQc6s5KkLn1hCRkXfy3B8lUJmxbb/F8KQR2F6IpM=
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    on_success: change
