# Use global defaults for all steps
# https://circleci.com/docs/2.0/workflows/#using-workspaces-to-share-data-among-jobs
# https://circleci.com/docs/2.0/configuration-reference/#persist_to_workspace
# https://github.com/circleci/frontend/blob/master/.circleci/config.yml
# Caching https://circleci.com/docs/2.0/caching/
defaults: &defaults
  working_directory: ~/colormaps-client
  docker:
      - image: circleci/node

workspace_root: &workspace_root
    .

attach_workspace: &attach_workspace
  attach_workspace:
    at: *workspace_root

repo_cache_key: &repo_cache_key
    repo-{{ .Branch }}-{{ .Revision }}

restore_repo: &restore_repo
  restore_cache:
    keys:
      - *repo_cache_key
      - repo-{{ .Branch }}
      - repo

npm_cache_key: &npm_cache_key
   packages-v1-{{ checksum "package.json" }}-{{ checksum "apps/api/package.json" }}-{{ checksum "apps/docs/package.json" }}-{{ checksum "yarn.lock" }}

restore_node_modules: &restore_node_modules
  restore_cache:
    keys:
      - *npm_cache_key

version: 2.0

jobs:
  checkout_code:
    <<: *defaults
    steps:
      - *restore_repo
      - checkout
      - save_cache:
          key: *repo_cache_key
          paths:
            - .
  install_deps:
    <<: *defaults
    steps:
      - *restore_repo
      - *restore_node_modules
      - run: yarn install --pure-lockfile --non-interactive
      - save_cache:
          key: *npm_cache_key
          paths:
            - node_modules
  test:
    <<: *defaults
    steps:
      - *restore_repo
      - *restore_node_modules
      - run:
          name: Run tests
          command: yarn test:cov
  build:
    <<: *defaults
    steps:
      - *restore_repo
      - *restore_node_modules
      - run:
          name: Build package
          no_output_timeout: 10m
          command: |
              yarn build
      - persist_to_workspace:
          root: .
          paths:
            - dist
  deploy:
    <<: *defaults
    steps:
      - *restore_repo
      - *attach_workspace
      - run:
          name: Publish package
          no_output_timeout: 15m
          command: |
              ./scripts/ci_deploy_app.sh apps/api

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - checkout_code
      - install_deps:
          requires:
            - checkout_code
      - test:
          requires:
            - install_deps
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
